trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      sudo apt update
      sudo apt upgrade -y
      curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      sudo apt install -y nodejs
  - bash: |
      npm install
      npm run export      
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: '/out'
      azure_static_web_apps_api_token: $(deployment_token)